import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.container}>
				<div className={styles.grid}>
					<Link href="/user">
						<div className={styles.card}>
							<a>User</a>
						</div>
					</Link>
				</div>
			</div>
		</div>
	)
}
